service-type = "TN"
data-dir = "./mo-data"

[log]
level = "info"

[tn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 19000

[malloc]
check-fraction = 65536
enable-metrics = true

[tn.Ckp]
flush-interval = "3s"
min-count = 10
scan-interval = "2s"
incremental-interval = "10s"
global-min-count = 2